name: Build
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8
      - name: Run JUnits
        run: ./gradlew testDebugUnitTest
      - name: Build the app
        run: ./gradlew build